### ISSUE TITLE
v3.0.1 exception: returned a promise and also uses a callback

### ISSUE THREAD

**Issue by dnalborczyk** [drager/serverless-hapi#2]
first of all, thank you for putting all of this together!

I'm getting an exception with **v3.0.1** and serverless-offline (also tried latest)

```shell
Serverless: Warning: handler 'hello' returned a promise and also uses a callback!
This is problematic and might cause issues in your lambda.
```

you can easily reproduce with `/example/hello`, when you install the `npm` version instead of directly referencing the project:

in `example/hello`:

```shell
npm i serverless-hapi`

```
then switch out the module references:
```javascript
// import {serverlessHapi, ResponseData} from '../../src/index'
import {serverlessHapi, ResponseData} from 'serverless-hapi'
```

when I install the `HEAD of master` everything works fine.

```shell
npm i drager/serverless-hapi
```

I suppose you fixed the issue in the commits after the release. could you deploy a new version perhaps?

**Comment by SimonStiph** [comment]
I can confirm this error exists when using the latest versions of both serverless-offline and serverless-hapi. In my case, as long as I stay with serverless-offline around version 3.25.17 I'm still able to use both of the latest version of serverless-hapi.

**Comment by drager** [comment]
@dnalborczyk @SimonStiph Sorry for my late answer, I apparently had notifications turned off for this repository for some weird reason... (Now I turned them on) I will release a version based on master right away! Sorry for the inconvenience.

**Comment by dnalborczyk** [comment]
@drager awesome! thank you!

**Comment by drager** [comment]
@dnalborczyk @SimonStiph Released at npm as 3.0.2: https://www.npmjs.com/package/serverless-hapi/v/3.0.2

Please let me know if that works as it should.

**Comment by dnalborczyk** [comment]
looking good as far as I can tell!

thanks again!

**Comment by SimonStiph** [comment]
Awesome. That did the trick. Thanks guys

**Comment by drager** [comment]
Great! Closing this then.
